import player1 from "../assets/c1.jpeg";
import player2 from "../assets/c1.jpeg";

export const cardsDB = [
  { id: 0, suit: "spades", value: 0, src: player1 },
  { id: 1, suit: "spades", value: 1, src: player1 },
  { id: 2, suit: "spades", value: 2, src: player1 },
  { id: 3, suit: "spades", value: 3, src: player1 },
  { id: 4, suit: "spades", value: 4, src: player1 },
  { id: 5, suit: "spades", value: 5, src: player1 },
  { id: 6, suit: "spades", value: 6, src: player1 },
  { id: 7, suit: "spades", value: 7, src: player1 },
  { id: 8, suit: "spades", value: 8, src: player1 },
  { id: 9, suit: "spades", value: 9, src: player1 },
  { id: 10, suit: "spades", value: 10, src: player1 },
  { id: 11, suit: "spades", value: 11, src: player1 },
  { id: 12, suit: "spades", value: 12, src: player1 },
  { id: 13, suit: "spades", value: 13, src: player1 },

  { id: 14, suit: "hearts", value: 0, src: player2 },
  { id: 15, suit: "hearts", value: 1, src: player2 },
  { id: 16, suit: "hearts", value: 2, src: player2 },
  { id: 17, suit: "hearts", value: 3, src: player2 },
  { id: 18, suit: "hearts", value: 4, src: player2 },
  { id: 19, suit: "hearts", value: 5, src: player2 },
  { id: 20, suit: "hearts", value: 6, src: player2 },
  { id: 21, suit: "hearts", value: 7, src: player2 },
  { id: 22, suit: "hearts", value: 8, src: player2 },
  { id: 23, suit: "hearts", value: 9, src: player2 },
  { id: 24, suit: "hearts", value: 10, src: player2 },
  { id: 25, suit: "hearts", value: 11, src: player2 },
  { id: 26, suit: "hearts", value: 12, src: player2 },
  { id: 27, suit: "hearts", value: 13, src: player2 },

  { id: 28, suit: "clubs", value: 0, src: player1 },
  { id: 29, suit: "clubs", value: 1, src: player1 },
  { id: 30, suit: "clubs", value: 2, src: player1 },
  { id: 31, suit: "clubs", value: 3, src: player1 },
  { id: 32, suit: "clubs", value: 4, src: player1 },
  { id: 33, suit: "clubs", value: 5, src: player1 },
  { id: 34, suit: "clubs", value: 6, src: player1 },
  { id: 35, suit: "clubs", value: 7, src: player1 },
  { id: 36, suit: "clubs", value: 8, src: player1 },
  { id: 37, suit: "clubs", value: 9, src: player1 },
  { id: 38, suit: "clubs", value: 10, src: player1 },
  { id: 39, suit: "clubs", value: 11, src: player1 },
  { id: 40, suit: "clubs", value: 12, src: player1 },
  { id: 41, suit: "clubs", value: 13, src: player1 },

  { id: 42, suit: "diamonds", value: 0, src: player1 },
  { id: 43, suit: "diamonds", value: 1, src: player1 },
  { id: 44, suit: "diamonds", value: 2, src: player1 },
  { id: 45, suit: "diamonds", value: 3, src: player1 },
  { id: 46, suit: "diamonds", value: 4, src: player1 },
  { id: 47, suit: "diamonds", value: 5, src: player1 },
  { id: 48, suit: "diamonds", value: 6, src: player1 },
  { id: 49, suit: "diamonds", value: 7, src: player1 },
  { id: 50, suit: "diamonds", value: 8, src: player1 },
  { id: 51, suit: "diamonds", value: 9, src: player1 },
  { id: 52, suit: "diamonds", value: 10, src: player1 },
  { id: 53, suit: "diamonds", value: 11, src: player1 },
  { id: 54, suit: "diamonds", value: 12, src: player1 },
  { id: 55, suit: "diamonds", value: 13, src: player1 },
];
