import sp from "../assets/dc1.jpg";
import he from "../assets/kk13.jpg";
import di from "../assets/kingH.png";
import cl from "../assets/jss.png";

export const cardsDB = [
  { id: 0, suit: "spades", value: 1, src: sp },
  { id: 1, suit: "spades", value: 2, src: sp },
  { id: 2, suit: "spades", value: 3, src: sp },
  { id: 3, suit: "spades", value: 4, src: sp },
  { id: 4, suit: "spades", value: 5, src: sp },
  { id: 5, suit: "spades", value: 6, src: sp },
  { id: 6, suit: "spades", value: 7, src: sp },
  { id: 7, suit: "spades", value: 8, src: sp },
  { id: 8, suit: "spades", value: 9, src: sp },
  { id: 9, suit: "spades", value: 10, src: sp },
  { id: 10, suit: "spades", value: 11, src: sp },
  { id: 11, suit: "spades", value: 12, src: sp },
  { id: 12, suit: "spades", value: 13, src: sp },
  { id: 13, suit: "spades", value: 14, src: sp },
  { id: 14, suit: "hearts", value: 1, src: he },
  { id: 15, suit: "hearts", value: 2, src: he },
  { id: 16, suit: "hearts", value: 3, src: he },
  { id: 17, suit: "hearts", value: 4, src: he },
  { id: 18, suit: "hearts", value: 5, src: he },
  { id: 19, suit: "hearts", value: 6, src: he },
  { id: 20, suit: "hearts", value: 7, src: he },
  { id: 21, suit: "hearts", value: 8, src: he },
  { id: 22, suit: "hearts", value: 9, src: he },
  { id: 23, suit: "hearts", value: 10, src: he },
  { id: 24, suit: "hearts", value: 11, src: he },
  { id: 25, suit: "hearts", value: 12, src: he },
  { id: 26, suit: "hearts", value: 13, src: he },
  { id: 27, suit: "hearts", value: 14, src: he },
  { id: 28, suit: "diamonds", value: 1, src: di },
  { id: 29, suit: "diamonds", value: 2, src: di },
  { id: 30, suit: "diamonds", value: 3, src: di },
  { id: 31, suit: "diamonds", value: 4, src: di },
  { id: 32, suit: "diamonds", value: 5, src: di },
  { id: 33, suit: "diamonds", value: 6, src: di },
  { id: 34, suit: "diamonds", value: 7, src: di },
  { id: 35, suit: "diamonds", value: 8, src: di },
  { id: 36, suit: "diamonds", value: 9, src: di },
  { id: 37, suit: "diamonds", value: 10, src: di },
  { id: 38, suit: "diamonds", value: 11, src: di },
  { id: 39, suit: "diamonds", value: 12, src: di },
  { id: 40, suit: "diamonds", value: 13, src: di },
  { id: 41, suit: "diamonds", value: 14, src: di },
  { id: 42, suit: "clubs", value: 1, src: cl },
  { id: 43, suit: "clubs", value: 2, src: cl },
  { id: 44, suit: "clubs", value: 3, src: cl },
  { id: 45, suit: "clubs", value: 4, src: cl },
  { id: 46, suit: "clubs", value: 5, src: cl },
  { id: 47, suit: "clubs", value: 6, src: cl },
  { id: 48, suit: "clubs", value: 7, src: cl },
  { id: 49, suit: "clubs", value: 8, src: cl },
  { id: 50, suit: "clubs", value: 9, src: cl },
  { id: 51, suit: "clubs", value: 10, src: cl },
  { id: 52, suit: "clubs", value: 11, src: cl },
  { id: 53, suit: "clubs", value: 12, src: cl },
  { id: 54, suit: "clubs", value: 13, src: cl },
  { id: 55, suit: "clubs", value: 14, src: cl },
];
